# Generated by Django 2.2.4 on 2019-08-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=40, verbose_name='نام شعبه')),
                ('account_number', models.CharField(max_length=40, verbose_name='شماره حساب')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت')),
                ('shaba_number', models.CharField(blank=True, max_length=26, null=True, verbose_name='شماره شبا')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
            ],
        ),
    ]
